### ISSUE TITLE
[TU0 Xbox 360 Accuracy Assort Not Working] Crash upon entering tutorial world on macOS ARM Chip

### ISSUE THREAD

**Issue by Hand-Lock** [MC-Legacy-Projects/Legacy-Reborn#4]
Using latest 1.3.2 version. Creating a new world works fine, only tutorial seems to make it crash.
Previous versions worked great, including the tutorial world.
https://mclo.gs/giAlp80

**Comment by Permdog99** [comment]
Did you update any mods?

**Comment by fytuf** [comment]
this doesnt seem to happen to me on java 22 macos 15.1 on M2 running the same version
<img width="1652" alt="Screenshot 2024-10-13 at 4 47 33 PM" src="https://github.com/user-attachments/assets/239ede2f-1605-403b-972d-c5774c1468f8">


i tried making a tutorial world on java 17 as you were on the same version and it functioned normally
<img width="1100" alt="Screenshot 2024-10-13 at 4 49 25 PM" src="https://github.com/user-attachments/assets/e05fb67d-6154-45f8-ad98-e9bdba70233a">
what macos version are you using?

**Comment by Hand-Lock** [comment]
Got it, it's the X360 T0 parity resource assort. If I disable it the tutorial world works fine.

**Comment by Permdog99** [comment]
Others have been getting the same errors regarding the assort. A patch will come out soon to try and fix this
